



CREATE TABLE IF NOT EXISTS Events (
id INTEGER PRIMARY KEY,
title TEXT NOT NULL UNIQUE,
description TEXT,
poster TEXT,
date DATE NULL,
is_featured BOOLEAN NOT NULL DEFAULT False
);





CREATE TABLE IF NOT EXISTS Users (
id INTEGER PRIMARY KEY,
name TEXT NOT NULL UNIQUE,
email TEXT NOT NULL,
password TEXT NOT NULL UNIQUE,
phone TEXT,
birthday DATE,
is_admin BOOLEAN NOT NULL DEFAULT False
);