CREATE TABLE IF NOT EXISTS Day (
id INTEGER PRIMARY KEY,
name TEXT NOT NULL UNIQUE 
);



CREATE TABLE IF NOT EXISTS Events (
id INTEGER PRIMARY KEY,
title TEXT NOT NULL UNIQUE,
description TEXT,
poster TEXT,
is_featured BOOLEAN NOT NULL DEFAULT False
);



CREATE TABLE IF NOT EXISTS Date (
id INTEGER PRIMARY KEY,
Day_id INTEGER,
Event_id INTEGER,
FOREIGN KEY (Day_id) REFERENCES Day (id)
FOREIGN KEY (Event_id) REFERENCES Event (id)
);



CREATE TABLE IF NOT EXISTS Users (
id INTEGER PRIMARY KEY,
name TEXT NOT NULL UNIQUE,
email TEXT NOT NULL,
password TEXT NOT NULL UNIQUE,
phone TEXT,
birthday DATE,
is_admin BOOLEAN NOT NULL DEFAULT False
);